name = "LatticeHamiltonian"
uuid = "975dfee0-c77a-4875-9b7e-98d523def842"
authors = ["mary <maryprimary@outlook.com>"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
